# Generated by Django 2.2 on 2019-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('alignment', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('eye_color', models.CharField(max_length=300)),
                ('race', models.CharField(max_length=300)),
                ('hair_color', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('skin_color', models.CharField(max_length=300)),
                ('height', models.CharField(max_length=300)),
                ('intelligence', models.CharField(max_length=300)),
                ('strength', models.CharField(max_length=300)),
                ('speed', models.CharField(max_length=300)),
                ('durability', models.CharField(max_length=300)),
                ('power', models.CharField(max_length=300)),
                ('combat', models.CharField(max_length=300)),
            ],
        ),
    ]
