# Generated by Django 2.2 on 2019-04-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_hero_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='weight',
            field=models.CharField(default=100, max_length=300),
            preserve_default=False,
        ),
    ]
