# Generated by Django 2.2 on 2019-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_hero_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='combat',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='durability',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='eye_color',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hair_color',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='height',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='intelligence',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='publisher',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skin_color',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='speed',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weight',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
