# Generated by Django 2.2 on 2019-06-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_auto_20190523_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/380x280.png?text=Hero', null=True),
        ),
    ]
