# Generated by Django 2.2 on 2019-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_secret',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
